name: Deploy pipeline

on:
  push:
    branches: [master, develop]
  pull_request:
    types: [opened, synchronize]


jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 16
      - name: Install dependencies
        run: npm ci

  build:
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/upload-artifacts@v2
        with:
          name: dist
          path: dist

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - uses: actions/download-artifacts@v2
        with:
          name: dist
          path: dist
      - name: Test
        run: npm run test

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Comming soon deply
        run: echo "Comming soon deply"


concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
